package org.example.newwsdlfile;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-04-14T15:25:54.451+03:00
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "NewWSDLFile",
                  wsdlLocation = "file:/c:/ws/mock/mock/NewWSDLFile.wsdl",
                  targetNamespace = "http://www.example.org/NewWSDLFile/")
public class NewWSDLFile_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/NewWSDLFile/", "NewWSDLFile");
    public final static QName NewWSDLFileSOAP = new QName("http://www.example.org/NewWSDLFile/", "NewWSDLFileSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/c:/ws/mock/mock/NewWSDLFile.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(NewWSDLFile_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/c:/ws/mock/mock/NewWSDLFile.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public NewWSDLFile_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public NewWSDLFile_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NewWSDLFile_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public NewWSDLFile_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public NewWSDLFile_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public NewWSDLFile_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns NewWSDLFile
     */
    @WebEndpoint(name = "NewWSDLFileSOAP")
    public NewWSDLFile getNewWSDLFileSOAP() {
        return super.getPort(NewWSDLFileSOAP, NewWSDLFile.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NewWSDLFile
     */
    @WebEndpoint(name = "NewWSDLFileSOAP")
    public NewWSDLFile getNewWSDLFileSOAP(WebServiceFeature... features) {
        return super.getPort(NewWSDLFileSOAP, NewWSDLFile.class, features);
    }

}
